name: Deploy to GitHub Pages (branch)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Ensure pnpm is available before setup-node cache tries to use it
      - name: Set up pnpm (from package.json)
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Show pnpm version
        run: pnpm -v

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        env:
          # Mark this as a CI build for Pages so Vite picks the correct base
          GITHUB_ACTIONS: 'true'
        run: pnpm build

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/spa
          publish_branch: gh-pages
          enable_jekyll: false
          force_orphan: true
